import type { Metadata } from "next";
import { SITE_URL } from "@/lib/products";

export const metadata: Metadata = {
  title: "Privacy Policy",
  description: "How WitUS handles your data across every platform in the ecosystem.",
  alternates: { canonical: `${SITE_URL}/privacy` },
  openGraph: {
    title: "Privacy Policy · WitUS",
    description:
      "How WitUS handles your data across every platform in the ecosystem.",
    url: `${SITE_URL}/privacy`,
    images: [
      {
        url: "/og/privacy",
        width: 1200,
        height: 630,
        alt: "Privacy Policy.",
      },
    ],
  },
  twitter: {
    card: "summary_large_image",
    title: "Privacy Policy · WitUS",
    description:
      "How WitUS handles your data across every platform in the ecosystem.",
    images: ["/og/privacy"],
  },
};

export default function PrivacyPage() {
  return (
    <div className="max-w-3xl mx-auto px-6 py-20">
      <p className="text-sm font-semibold tracking-widest text-slate-400 uppercase mb-4">Legal</p>
      <h1 className="text-4xl font-extrabold text-white mb-2 leading-tight">Privacy Policy</h1>
      <p className="text-slate-400 text-sm mb-12">Last updated: March 2026</p>

      <div className="space-y-10 text-slate-400 leading-relaxed">
        <section>
          <h2 className="text-lg font-bold text-white mb-3">1. Who we are</h2>
          <p>
            WitUS.online and all associated platforms (CentenarianOS, Work.WitUS) are operated by
            B4C LLC / AwesomeWebStore.com, based in Indianapolis, Indiana. Contact us at{" "}
            <a
              href="mailto:admin@centenarianos.com"
              className="text-slate-300 hover:text-white transition-colors"
            >
              admin@CentenarianOS.com
            </a>
            .
          </p>
        </section>

        <section>
          <h2 className="text-lg font-bold text-white mb-3">2. Data we collect</h2>
          <p className="mb-3">
            We collect information you provide directly (account credentials, profile data, content
            you enter) and technical data generated by your use of the platforms (usage analytics,
            device information, IP addresses).
          </p>
          <p>
            Health and financial data entered into CentenarianOS, and job/invoice data entered into
            Work.WitUS, are stored privately and are never sold or shared with third parties.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-bold text-white mb-3">3. How we use your data</h2>
          <ul className="list-disc list-inside space-y-1 text-sm">
            <li>To provide and improve platform features</li>
            <li>To authenticate your account across platforms</li>
            <li>To process payments via Stripe</li>
            <li>To send transactional and account-related emails</li>
            <li>To generate AI-assisted features (Gemini API). Never used to train models</li>
          </ul>
        </section>

        <section>
          <h2 className="text-lg font-bold text-white mb-3">4. Data sharing</h2>
          <p>
            We share data only with service providers necessary to operate the platform: Supabase
            (database), Stripe (payments), Cloudinary (media storage), Vercel (hosting), and Google
            (Gemini AI features). We do not sell your data.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-bold text-white mb-3">5. Security</h2>
          <p>
            All data is encrypted in transit (TLS 1.3) and at rest (AES-256). Sensitive tables use
            Row Level Security to ensure users can only access their own data. We follow OWASP
            security best practices throughout the codebase.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-bold text-white mb-3">6. Your rights</h2>
          <p>
            You can export your data, request deletion of your account, or update your information
            at any time from within the platform settings. For data requests, contact{" "}
            <a
              href="mailto:admin@centenarianos.com"
              className="text-slate-300 hover:text-white transition-colors"
            >
              admin@CentenarianOS.com
            </a>
            .
          </p>
        </section>

        <section>
          <h2 className="text-lg font-bold text-white mb-3">7. Cookies</h2>
          <p>
            We use session cookies for authentication and analytics cookies (Vercel Analytics) to
            understand platform usage. No third-party advertising cookies are used.
          </p>
        </section>
      </div>
    </div>
  );
}
